// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-77xB1b_h2TpVeAD8cMHFXlHuXAssI8',
    appId: '1:591360662712:web:27cc791eb7718e003ce84d',
    messagingSenderId: '591360662712',
    projectId: 'ui00-2aede',
    authDomain: 'ui00-2aede.firebaseapp.com',
    storageBucket: 'ui00-2aede.appspot.com',
    measurementId: 'G-2XW9THWJBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0AVevcfWvNAdQbFuL5fcbhvEZ02mXuCM',
    appId: '1:591360662712:android:afb4b57cf7e78afd3ce84d',
    messagingSenderId: '591360662712',
    projectId: 'ui00-2aede',
    storageBucket: 'ui00-2aede.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClVMXcl-nGLO8GK_1VesOtw3VKcBp_JNw',
    appId: '1:591360662712:ios:226a27adf8520bca3ce84d',
    messagingSenderId: '591360662712',
    projectId: 'ui00-2aede',
    storageBucket: 'ui00-2aede.appspot.com',
    iosBundleId: 'com.example.ui0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClVMXcl-nGLO8GK_1VesOtw3VKcBp_JNw',
    appId: '1:591360662712:ios:226a27adf8520bca3ce84d',
    messagingSenderId: '591360662712',
    projectId: 'ui00-2aede',
    storageBucket: 'ui00-2aede.appspot.com',
    iosBundleId: 'com.example.ui0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-77xB1b_h2TpVeAD8cMHFXlHuXAssI8',
    appId: '1:591360662712:web:4d46fda2e996cd783ce84d',
    messagingSenderId: '591360662712',
    projectId: 'ui00-2aede',
    authDomain: 'ui00-2aede.firebaseapp.com',
    storageBucket: 'ui00-2aede.appspot.com',
    measurementId: 'G-SCHK01W9P3',
  );
}
